name: copilot
base: core24
version: '0.1'
summary: Copilot Wrapper
description: |
  Copilot Wrapper is a versatile application designed to bridge the gap between the web version of Copilot and the Windows app experience.
  This lightweight wrapper ensures that you enjoy the full functionality and intuitive interface of Copilot right from your desktop,
  providing a seamless and integrated user experience.

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: nil
    source: .
    override-build: |
      chmod +x setup.sh
      ./setup.sh install
    build-packages:
      - build-essential

apps:
  copilot:
    command: bin/copilot
    plugs:
      - network
      - home
